# Generated by Django 3.0.3 on 2020-02-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbag',
            name='total_ml',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
