# Generated by Django 3.0.3 on 2020-02-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_auto_20200224_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='address',
            field=models.TextField(default='abcd', max_length=400),
            preserve_default=False,
        ),
    ]
