# Generated by Django 3.0.3 on 2020-02-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0004_bloodbank_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='latitude',
            field=models.CharField(default=20.78976, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='longitude',
            field=models.CharField(default=45.76512, max_length=20),
            preserve_default=False,
        ),
    ]
