# Generated by Django 3.0.3 on 2020-02-26 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_auto_20200225_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbag',
            name='total_ml',
        ),
        migrations.CreateModel(
            name='TotalBlood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ml', models.IntegerField()),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_blood', to='banks.BloodBank')),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_blood', to='banks.BloodGroup')),
            ],
        ),
    ]
